energy_optimizer:
  module: energy_optimizer
  class: EnergyOptimizer
  optimization_period: 300       # seconds (5 min)
  battery_charge_current: 25     # amps
  min_soc: 80
  target_soc: 100
  boiler_temp_min: 55
  boiler_temp_optimal: 70
  min_spot_price: 300            # CZK/MWh
