name: "Energy Optimizer"
version: "1.0.0"
slug: "energy_optimizer"
description: "AppDaemon add-on for energy optimization"
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
  - i386
startup: application
boot: auto
hassio_api: true
hassio_role: default
options:
  optimization_period: 300
  battery_charge_current: 25
  min_soc: 80
  opt_soc: 100
  min_boiler_temp: 55
  opt_boiler_temp: 70
  min_spot_price: 300
  min_grid_charge_soc: 20
  timezone: "UTC"
  latitude: 50.08804
  longitude: 14.42076
  elevation: 200
schema:
  optimization_period: int
  battery_charge_current: int
  min_soc: int
  opt_soc: int
  min_boiler_temp: int
  opt_boiler_temp: int
  min_spot_price: int
  min_grid_charge_soc: int
  timezone: str
  latitude: float
  longitude: float
  elevation: int
