views:
  - title: Energy Optimizer
    path: energy-optimizer
    icon: mdi:solar-power
    cards:
      # --- Current State Grid ---
      - type: grid
        title: Current System State
        columns: 3
        cards:
          - type: entity
            entity: sensor.solax_battery_capacity
            name: Battery SoC
            icon: mdi:battery
          - type: entity
            entity: sensor.solax_pv_power_total
            name: PV Power
            icon: mdi:solar-power
          - type: entity
            entity: sensor.solax_house_load
            name: House Load
            icon: mdi:home-lightning-bolt
          - type: entity
            entity: sensor.boiler_temp
            name: Boiler Temp
            icon: mdi:water-boiler
          - type: entity
            entity: sensor.current_spot_electricity_price
            name: Spot Price
            icon: mdi:currency-eur
          - type: entities
            title: Actuators
            entities:
              - switch.boiler_relay_1
              - switch.boiler_relay_2
              - number.solax_battery_charge_max_current
              - number.solax_export_control_user_limit

      # --- Historical Chart: Plan vs Actual ---
      - type: custom:apexcharts-card
        header:
          title: Energy Plan vs Actual
          show: true
        graph_span: 7d
        update_interval: 5min
        all_series_config:
          stroke_width: 2
        series:
          - entity: sensor.solax_pv_power_total
            name: PV Production
            type: area
            group_by:
              duration: 1h
              func: avg
          - entity: sensor.solax_house_load
            name: House Load
            type: area
            group_by:
              duration: 1h
              func: avg
          - entity: number.solax_export_control_user_limit
            name: Grid Export Limit (Plan)
            type: line
            color: red
            group_by:
              duration: 1h
              func: avg
          - entity: sensor.current_spot_electricity_price
            name: Spot Price
            type: line
            yaxis_id: price
            stroke_width: 1
            color: orange
        yaxis:
          - id: default
            opposite: false
            min: 0
          - id: price
            opposite: true
            min: 0
